const Colors = {
  PRIMARY: "#007AFF",
  MAIN_BACKGROUND: "#121212",
  // MAIN_NAVIGATION_BACKGROUND: "#2A2A2A",
  MAIN_NAVIGATION_BACKGROUND: "#363636",
  NAVIGATION_INACTIVE_TEXT: "#A1A1A1",
  SECONDARY: "#FFFFFF",
  COMPONENT_BACKGROUND: "#1E1E1E"
}

export default Colors;