const KLIK_CODE_TIME = 20;
const KLIK_PAYMENT_TIME = 60;
const BEARER_PREFIX = "Bearer ";
const REST_PATH_ACCOUNT = 'http://192.168.100.121:80/api/account';
const REST_PATH_TRANSFER = 'http://192.168.100.121:80/api/transfer';

export {
    KLIK_CODE_TIME,
    KLIK_PAYMENT_TIME,
    BEARER_PREFIX,
    REST_PATH_ACCOUNT,
    REST_PATH_TRANSFER
}