const KLIK_CODE_TIME = 120;
const KLIK_PAYMENT_TIME = 60;
const BEARER_PREFIX = "Bearer ";
const REST_PATH_AUTH = 'http://127.0.0.1:80/api/web';
const REST_PATH_ACCOUNT = 'http://192.168.101.111:80/api/account'

export {
  KLIK_CODE_TIME,
  KLIK_PAYMENT_TIME,
  BEARER_PREFIX,
  REST_PATH_AUTH,
  REST_PATH_ACCOUNT
  
}